### ISSUE TITLE
feat: docker / docker-compose support

### ISSUE THREAD

**Issue by sammcj** [Kiln-AI/Kiln#73]
Love the project!

It would be great if kiln could be spun up in a container, this would make it a lot easier for folks to run across multiple environments and would mean they could run it on a powerful machine (e.g. with Ollama + GPUs).

I actually have this working, but I'm doing a _really_ gross hack, I'll include what's working for me below as I think the general dockerfile and compose example is OK but of course rather than injecting the disgusting server.py (sorry I was in a rush 🤣) you could probably integrate it into the app directly.

```Dockerfile
# Stage 1: Build the web UI
FROM node:22-slim AS web-builder

WORKDIR /app

# Clone the repository
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/* && \
  git clone https://github.com/Kiln-AI/Kiln .

# Build web UI
WORKDIR /app/app/web_ui

# Install dependencies
RUN npm install -g pnpm && \
  pnpm install

# Update API client to use relative URLs
RUN sed -i 's|baseUrl: "http://localhost:8757"|baseUrl: ""|g' src/lib/api_client.ts

# Build the web UI
RUN pnpm run build

# Stage 2: Python environment
FROM python:3.12-slim

WORKDIR /app

# Install system dependencies and clone repo
RUN apt-get update && apt-get install -y \
  build-essential \
  git \
  && rm -rf /var/lib/apt/lists/* \
  && git clone https://github.com/Kiln-AI/Kiln .

# Install Python dependencies
RUN pip install --no-cache-dir -e ./libs/core \
  && pip install --no-cache-dir -e ./libs/server

# Copy built web UI
COPY --from=web-builder /app/app/web_ui/build /app/app/web_ui/build

# Create simple server.py
RUN echo 'from fastapi import FastAPI\nfrom fastapi.middleware.cors import CORSMiddleware\nfrom kiln_server.server import make_app\nfrom app.desktop.studio_server.webhost import HTMLStaticFiles, studio_path\nfrom app.desktop.studio_server.provider_api import connect_provider_api\nfrom app.desktop.studio_server.settings_api import connect_settings\nfrom app.desktop.studio_server.data_gen_api import connect_data_gen_api\nfrom app.desktop.studio_server.finetune_api import connect_fine_tune_api\nfrom app.desktop.studio_server.prompt_api import connect_prompt_api\nfrom app.desktop.studio_server.repair_api import connect_repair_api\n\n# Create base app with API routes\napp = make_app()\n\n# Add CORS middleware\napp.add_middleware(\n    CORSMiddleware,\n    allow_origins=["*"],\n    allow_credentials=True,\n    allow_methods=["*"],\n    allow_headers=["*"],\n    expose_headers=["*"],\n    max_age=86400\n)\n\n# Add studio server routes\nconnect_provider_api(app)\nconnect_settings(app)\nconnect_data_gen_api(app)\nconnect_fine_tune_api(app)\nconnect_prompt_api(app)\nconnect_repair_api(app)\n\n# Serve static files last\napp.mount("/", HTMLStaticFiles(directory=studio_path(), html=True), name="studio")' > /app/server.py

# Update langchain adapter for Ollama
RUN sed -i 's|return ChatOllama(model=model_name, base_url=ollama_base_url())|return ChatOllama(model=model_name, base_url=ollama_base_url(), format="json")|g' /app/libs/core/kiln_ai/adapters/langchain_adapters.py

# Set environment variables
ENV PYTHONPATH=/app
ENV KILN_WEB_UI_PATH=/app/app/web_ui/build
ENV ALLOW_ALL_ORIGINS=1
ENV NODE_ENV=development
ENV OLLAMA_BASE_URL=http://ollama:11434

# Run the server
CMD ["python", "-m", "uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "debug"]
```

Example compose:

```yaml

services:
  kiln:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - KILN_WEB_UI_PATH=/app/app/web_ui/build
      - OLLAMA_BASE_URL=http://ollama:11434
      - ALLOW_ALL_ORIGINS=1
      - NODE_ENV=development
    volumes:
      - kiln_config:/root/.kiln_ai
      - kiln_data:/data
    restart: unless-stopped
    # depends_on:
    #   - ollama

volumes:
  kiln_config:
    name: kiln_config
  kiln_data:
    name: kiln_data
```
